# Generated by Django 3.1.6 on 2021-02-28 21:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verdura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('abacate', models.IntegerField(default=0)),
                ('abacaxi', models.IntegerField(default=0)),
                ('abobrinha', models.IntegerField(default=0)),
                ('alface', models.IntegerField(default=0)),
                ('alho_poro', models.IntegerField(default=0, verbose_name='Alho Poró')),
                ('batata', models.DecimalField(decimal_places=2, default=0, help_text='Quantidade de Batatas x 0.13', max_digits=5, verbose_name='Batata (kg)')),
                ('batata_doce', models.IntegerField(default=0)),
                ('brocolis', models.IntegerField(default=0)),
                ('cabeca_de_alho', models.IntegerField(default=0, verbose_name='Cabeça de Alho')),
                ('cebola', models.DecimalField(decimal_places=2, default=0, help_text='Quantidade de Cebolas x 0.15', max_digits=5, verbose_name='Cebola (kg)')),
                ('cebola_roxa', models.IntegerField(default=0, verbose_name='Cebola Roxa')),
                ('cenoura', models.DecimalField(decimal_places=2, default=0, help_text='Quantidade de Cenouras x 0.2', max_digits=5, verbose_name='Cenoura (kg)')),
                ('coco', models.IntegerField(default=0)),
                ('cheiro_verde', models.IntegerField(default=0, verbose_name='Cheiro Verde')),
                ('chuchu', models.IntegerField(default=0)),
                ('couve_flor', models.IntegerField(default=0, verbose_name='Couve Flor')),
                ('couve_folha', models.IntegerField(default=0, verbose_name='Couve Folha')),
                ('banana', models.DecimalField(decimal_places=2, default=0, help_text='Dúzias em valor decimal.', max_digits=5, verbose_name='Dúzias de Banana')),
                ('espinafre', models.IntegerField(default=0)),
                ('laranja', models.IntegerField(default=0)),
                ('maca', models.IntegerField(default=0, verbose_name='Maçã')),
                ('macaxeira', models.IntegerField(default=0)),
                ('mamao', models.IntegerField(default=0, verbose_name='Mamão')),
                ('maracuja', models.IntegerField(default=0, verbose_name='Maracujá')),
                ('pepino', models.IntegerField(default=0)),
                ('pimenta_de_cheiro', models.IntegerField(default=0, verbose_name='Pimenta de Cheiro')),
                ('pimentao', models.IntegerField(default=0, verbose_name='Pimentão')),
                ('tangerina', models.IntegerField(default=0)),
                ('tomate', models.DecimalField(decimal_places=2, default=0, help_text='Quantidade de Tomates x 0.15', max_digits=5)),
                ('rucula', models.IntegerField(default=0, verbose_name='Rúcula')),
                ('quiabo', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome igual o do seu Login.', max_length=50)),
                ('data', models.DateField(default=datetime.date.today)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
