# Generated by Django 3.1.6 on 2021-02-12 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='descricao',
        ),
        migrations.AddField(
            model_name='campo',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
    ]
