# Generated by Django 3.1.6 on 2021-02-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20210212_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='campo',
            name='data',
        ),
    ]
