# Generated by Django 3.1.6 on 2021-02-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20210213_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.AddField(
            model_name='campo',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
