# Generated by Django 3.1.6 on 2021-02-13 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20210213_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verdura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='campo',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
