# Generated by Django 3.1.6 on 2021-02-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_verdura_lista_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verdura',
            name='lista_final',
        ),
    ]
