# Generated by Django 3.1.6 on 2021-02-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_remove_verdura_lista_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdura',
            name='abacate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='abacaxi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='abobrinha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='alface',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='alho_poro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='banana',
            field=models.IntegerField(default=0),
        ),
    ]
