# Generated by Django 3.1.6 on 2021-02-14 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_auto_20210213_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verdura',
            name='abacate',
        ),
        migrations.RemoveField(
            model_name='verdura',
            name='abacaxi',
        ),
        migrations.RemoveField(
            model_name='verdura',
            name='abobrinha',
        ),
        migrations.RemoveField(
            model_name='verdura',
            name='alface',
        ),
        migrations.RemoveField(
            model_name='verdura',
            name='alho_poro',
        ),
        migrations.RemoveField(
            model_name='verdura',
            name='banana',
        ),
    ]
