# Generated by Django 3.1.6 on 2021-02-14 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_auto_20210214_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdura',
            name='abacate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='abacaxi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='abobrinha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='alface',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='alho_poro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='banana',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Dúzias de Banana'),
        ),
        migrations.AddField(
            model_name='verdura',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.campo'),
            preserve_default=False,
        ),
    ]
