# Generated by Django 3.1.6 on 2021-02-16 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0010_auto_20210214_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='logado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verdura',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campo',
            name='nome',
            field=models.CharField(help_text='Digite o nome igual o do seu Login.', max_length=50),
        ),
        migrations.AlterField(
            model_name='verdura',
            name='banana',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Dúzias em valor decimal.', max_digits=4, verbose_name='Dúzias de Banana'),
        ),
    ]
