# Generated by Django 3.1.6 on 2021-02-16 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0013_atividade_campo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeasaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abacate', models.IntegerField(default=0)),
                ('abacaxi', models.IntegerField(default=0)),
                ('abobrinha', models.IntegerField(default=0)),
                ('alface', models.IntegerField(default=0)),
                ('alho_poro', models.IntegerField(default=0)),
                ('banana', models.DecimalField(decimal_places=1, default=0, help_text='Dúzias em valor decimal.', max_digits=4, verbose_name='Dúzias de Banana')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.campo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
