# Generated by Django 3.1.6 on 2021-02-17 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_auto_20210216_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceasamodel',
            name='abacate',
        ),
        migrations.RemoveField(
            model_name='ceasamodel',
            name='abacaxi',
        ),
        migrations.RemoveField(
            model_name='ceasamodel',
            name='abobrinha',
        ),
        migrations.RemoveField(
            model_name='ceasamodel',
            name='alface',
        ),
        migrations.RemoveField(
            model_name='ceasamodel',
            name='alho_poro',
        ),
        migrations.RemoveField(
            model_name='ceasamodel',
            name='banana',
        ),
        migrations.RemoveField(
            model_name='ceasamodel',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='ceasamodel',
            name='usuario',
        ),
        migrations.AddField(
            model_name='ceasamodel',
            name='v',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='verdura',
            name='data',
            field=models.DateField(default=datetime.date(2021, 2, 17)),
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
    ]
