# Generated by Django 3.1.6 on 2021-02-17 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_auto_20210217_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='verdura',
            name='batata',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Quantidade de Batata x 0,13', max_digits=4, verbose_name='Batata (kg)'),
        ),
        migrations.AddField(
            model_name='verdura',
            name='batata_doce',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='brocolis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='cebola',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='cebola_roxa',
            field=models.IntegerField(default=0, verbose_name='Cebola Roxa'),
        ),
        migrations.AddField(
            model_name='verdura',
            name='cenoura',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Quantidade de Cenoura x 0,2', max_digits=4, verbose_name='Cenoura (kg)'),
        ),
        migrations.AddField(
            model_name='verdura',
            name='cheiro_verde',
            field=models.IntegerField(default=0, verbose_name='Cheiro Verde'),
        ),
        migrations.AddField(
            model_name='verdura',
            name='chuchu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='coco',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='couve_flor',
            field=models.IntegerField(default=0, verbose_name='Couve Flor'),
        ),
        migrations.AddField(
            model_name='verdura',
            name='couve_folha',
            field=models.IntegerField(default=0, verbose_name='Couve Folha'),
        ),
        migrations.AddField(
            model_name='verdura',
            name='dente_de_alho',
            field=models.IntegerField(default=0, verbose_name='Dente de Alho'),
        ),
        migrations.AddField(
            model_name='verdura',
            name='espinafre',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='laranja',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='maca',
            field=models.IntegerField(default=0, verbose_name='Maçã'),
        ),
        migrations.AddField(
            model_name='verdura',
            name='macaxeira',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='mamao',
            field=models.IntegerField(default=0, verbose_name='Mamão'),
        ),
        migrations.AddField(
            model_name='verdura',
            name='maracuja',
            field=models.IntegerField(default=0, verbose_name='Maracujá'),
        ),
        migrations.AddField(
            model_name='verdura',
            name='pepino',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='pimenta_de_cheiro',
            field=models.IntegerField(default=0, verbose_name='Pimenta de Cheiro'),
        ),
        migrations.AddField(
            model_name='verdura',
            name='pimentao',
            field=models.IntegerField(default=0, verbose_name='Pimentão'),
        ),
        migrations.AddField(
            model_name='verdura',
            name='quiabo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='rucula',
            field=models.IntegerField(default=0, verbose_name='Rúcula'),
        ),
        migrations.AddField(
            model_name='verdura',
            name='tangerina',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verdura',
            name='tomate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='verdura',
            name='alho_poro',
            field=models.IntegerField(default=0, verbose_name='Alho Poró'),
        ),
        migrations.AlterField(
            model_name='verdura',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
