# Generated by Django 3.1.6 on 2021-02-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_auto_20210217_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verdura',
            name='dente_de_alho',
        ),
        migrations.AddField(
            model_name='verdura',
            name='cabeca_de_alho',
            field=models.IntegerField(default=0, verbose_name='Cabeça de Alho'),
        ),
        migrations.AlterField(
            model_name='verdura',
            name='cebola',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Cebola (kg)'),
        ),
        migrations.AlterField(
            model_name='verdura',
            name='tomate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
