# Generated by Django 3.1.6 on 2021-02-20 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0018_auto_20210217_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verdura',
            name='banana',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Dúzias em valor decimal.', max_digits=5, verbose_name='Dúzias de Banana'),
        ),
        migrations.AlterField(
            model_name='verdura',
            name='batata',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantidade de Batatas x 0.13', max_digits=5, verbose_name='Batata (kg)'),
        ),
        migrations.AlterField(
            model_name='verdura',
            name='cebola',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantidade de Cebolas x 0.15', max_digits=5, verbose_name='Cebola (kg)'),
        ),
        migrations.AlterField(
            model_name='verdura',
            name='cenoura',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantidade de Cenouras x 0.2', max_digits=5, verbose_name='Cenoura (kg)'),
        ),
        migrations.AlterField(
            model_name='verdura',
            name='tomate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantidade de Tomates x 0.15', max_digits=5),
        ),
        migrations.AlterField(
            model_name='verdura',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
