# Generated by Django 3.1.6 on 2021-02-20 11:43

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0019_auto_20210220_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verdura',
            name='usuario',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
