# Generated by Django 3.1.6 on 2021-02-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_auto_20210220_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
