# Generated by Django 3.1.6 on 2021-02-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_finalmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalModel',
        ),
        migrations.DeleteModel(
            name='Verdura',
        ),
    ]
