# Generated by Django 3.1.6 on 2021-02-28 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_finalmodel_verdura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeasaModel',
        ),
        migrations.DeleteModel(
            name='FinalModel',
        ),
    ]
